FROM rust:latest

ENV CARGO_BUILD_JOBS=1
ENV CARGO_INCREMENTAL=0

RUN apt-get update && apt-get install -y build-essential pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch

WORKDIR /app
COPY ./Cargo.toml ./Cargo.toml
COPY ./src ./src

CMD ["cargo", "watch", "-x", "run"]
